### ISSUE TITLE
[docs] sphinx

### ISSUE THREAD

**Issue by stonier** [splintered-reality/py_trees_ros_tutorials#18]
*  [x] basic sphinx build, #20
* [x] mock robot modules and launcher, #21
* [x] tutorial one - data gathering, #23
* [x] tutorial two - battery check, #24
* [x] tutorial three - blackboards
* [x] tutorial four - introspecting the tree
* [x] tutorial five - action clients
* [x] tutorial six - context switching
* [x] tutorial seven - docking, cancelling and failing
* [ ] tutorial eight - dynamic job handling
* [ ] tutorial nine - bagging
* [x] automated builds, #20

**Comment by stonier** [comment]
Classes that inherit from mocked classes do not show in autodocs for some reason. Some crumbs:

* https://stackoverflow.com/questions/25960309/sphinx-doc-automodule-with-mock-imports
* https://stackoverflow.com/questions/25893614/autodoc-a-class-that-extends-a-mocked-class?noredirect=1&lq=1

**Comment by stonier** [comment]
This got fixed in sphinx 1.7.5, [#4596](https://github.com/sphinx-doc/sphinx/issues/4956) and works under the `autodoc_mock_imports` mechanism.

Looks also like my concern with that and submodules is fixed by 1.8.5 as well. It does however have some other problems:

* Base class field gets populated now, but with `sphinx.ext.autodoc.importer._MockObject`
* Typehint return types are similarly with some Mock jibberish and not the mocked type (can work around by explicitly calling out the return type in napolean)

**Comment by stonier** [comment]
PyQt5 fails with autodoc (in `gui/main_window_rc.py`):

```
    if qt_version < ['5', '8', '0']:
TypeError: '<' not supported between instances of '_MockObject' and 'list'
```

**Comment by stonier** [comment]
Closing this one out, as the individual tutorial documentation is being handled at the same time as the code development, refer to #19.
