### ISSUE TITLE
[tutorials] one by one

### ISSUE THREAD

**Issue by stonier** [splintered-reality/py_trees_ros_tutorials#19]
* [x] tutorial one - data gathering, #23, #24
* [x] tutorial two - battery check, #24, 074b52dc
* [x] tutorial three - blackboards, #25
* [x] tutorial four - introspecting the tree, #26
* [x] tutorial five - action clients, #27
* [x] tutorial six - context switching, #28
* [x] tutorial seven - docking, cancelling and failing, #29
* [x] tutorial eight - dynamic job handling, #32 
* [ ] tutorial nine - bagging
