### ISSUE TITLE
[mock] migrate components to ROS2

### ISSUE THREAD

**Issue by stonier** [splintered-reality/py_trees_ros_tutorials#5]
**Mock**

* [x] Dynamic reconfigure Dashboard &rarr; #8, #9
* [x] Mock Dashboard &rarr; #8
* [x] Launcher &rarr; #8
* [x] Battery &rarr; #8
* [x] LED Strip
* [x] Fake Action Server &rarr; #10
* [ ] Action Server (https://github.com/ros2/rclpy/issues/257, https://github.com/ros2/rclpy/issues/270))
* [x] Dock &rarr; #10
* [x] Move Base &rarr; #11
* [x] Rotate &rarr; #10
* [x] Safety Sensors &rarr; #9

**Comment by stonier** [comment]
Still pending the arrival of the actual action server/client. Tracking that in #12 and closing this one out.
